In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [3]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [4]:
date["date"] = pd.to_datetime(date["date"])

In [5]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

**Extract Year**

In [6]:
date["Year"] = date["date"].dt.year
date

          date  product_id  city_id  orders  Year
0   2019-12-10        5628       25       3  2019
1   2018-08-15        3646       14     157  2018
2   2018-10-23        1859       25       1  2018
3   2019-08-17        7292       25       1  2019
4   2019-01-06        4344       25       3  2019
..         ...         ...      ...     ...   ...
995 2018-10-08         255       13       1  2018
996 2018-12-06        5521        7       1  2018
997 2019-05-07         487       26      14  2019
998 2019-03-03        1503       21       2  2019
999 2019-10-15        6371        7      22  2019

[1000 rows x 5 columns]

**Extract Months**

In [7]:
date["months"] = date["date"].dt.month
# date["months"] = date["date"].dt.month_name()

In [8]:
date

          date  product_id  city_id  orders  Year  months
0   2019-12-10        5628       25       3  2019      12
1   2018-08-15        3646       14     157  2018       8
2   2018-10-23        1859       25       1  2018      10
3   2019-08-17        7292       25       1  2019       8
4   2019-01-06        4344       25       3  2019       1
..         ...         ...      ...     ...   ...     ...
995 2018-10-08         255       13       1  2018      10
996 2018-12-06        5521        7       1  2018      12
997 2019-05-07         487       26      14  2019       5
998 2019-03-03        1503       21       2  2019       3
999 2019-10-15        6371        7      22  2019      10

[1000 rows x 6 columns]

**Extract Day**

In [13]:
date["Day"] = date["date"].dt.day
date.head()

        date  product_id  city_id  orders  Year  months  Day  Day_of_week
0 2019-12-10        5628       25       3  2019      12   10            1
1 2018-08-15        3646       14     157  2018       8   15            2
2 2018-10-23        1859       25       1  2018      10   23            1
3 2019-08-17        7292       25       1  2019       8   17            5
4 2019-01-06        4344       25       3  2019       1    6            6

In [15]:
date["Day_of_week"] = date["date"].dt.day_name()
date.head()

        date  product_id  city_id  orders  Year  months  Day Day_of_week
0 2019-12-10        5628       25       3  2019      12   10     Tuesday
1 2018-08-15        3646       14     157  2018       8   15   Wednesday
2 2018-10-23        1859       25       1  2018      10   23     Tuesday
3 2019-08-17        7292       25       1  2019       8   17    Saturday
4 2019-01-06        4344       25       3  2019       1    6      Sunday

**Checking Weekend or not**

In [16]:
# is weekend?
date['date_is_weekend'] = np.where(date['Day_of_week'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

        date  Year  months  Day Day_of_week  date_is_weekend
0 2019-12-10  2019      12   10     Tuesday                0
1 2018-08-15  2018       8   15   Wednesday                0
2 2018-10-23  2018      10   23     Tuesday                0
3 2019-08-17  2019       8   17    Saturday                1
4 2019-01-06  2019       1    6      Sunday                1

AttributeError: 'DatetimeProperties' object has no attribute 'week'