In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv("train.csv")[["Age", "Pclass", "SibSp", "Parch", "Survived"]]

In [3]:
df

      Age  Pclass  SibSp  Parch  Survived
0    22.0       3      1      0         0
1    38.0       1      1      0         1
2    26.0       3      0      0         1
3    35.0       1      1      0         1
4    35.0       3      0      0         0
..    ...     ...    ...    ...       ...
886  27.0       2      0      0         0
887  19.0       1      0      0         1
888   NaN       3      1      2         0
889  26.0       1      0      0         1
890  32.0       3      0      0         0

[891 rows x 5 columns]

In [4]:
df.dropna(inplace=True)

In [5]:
df

      Age  Pclass  SibSp  Parch  Survived
0    22.0       3      1      0         0
1    38.0       1      1      0         1
2    26.0       3      0      0         1
3    35.0       1      1      0         1
4    35.0       3      0      0         0
..    ...     ...    ...    ...       ...
885  39.0       3      0      5         0
886  27.0       2      0      0         0
887  19.0       1      0      0         1
889  26.0       1      0      0         1
890  32.0       3      0      0         0

[714 rows x 5 columns]

In [6]:
# Now lets calculate the accuracy(By Logistic regression model) on this dataset before applying feature construction
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

**Applying Feature Construction**

In [7]:
# Now lets create a new column which contains the total number of Family members
X["Family_Size"] = X["SibSp"] + X["Parch"] + 1

In [8]:
X

      Age  Pclass  SibSp  Parch  Family_Size
0    22.0       3      1      0            2
1    38.0       1      1      0            2
2    26.0       3      0      0            1
3    35.0       1      1      0            2
4    35.0       3      0      0            1
..    ...     ...    ...    ...          ...
885  39.0       3      0      5            6
886  27.0       2      0      0            1
887  19.0       1      0      0            1
889  26.0       1      0      0            1
890  32.0       3      0      0            1

[714 rows x 5 columns]

In [9]:
def fam(num):
    if num == 1:
        # Traveling alone
        return 0
    elif num > 1 and num <= 4:
        # Small family
        return 1
    else:
        # Large Family
        return 2

In [10]:
fam(5)  # Working

2

In [11]:
X["Family_Type"] = X["Family_Size"].apply(fam)

In [12]:
X.head()

    Age  Pclass  SibSp  Parch  Family_Size  Family_Type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [13]:
X.drop(columns=['SibSp','Parch','Family_Size'],inplace=True)
X.head()

    Age  Pclass  Family_Type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [14]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring="accuracy", cv=20)) # Accuracy increased

np.float64(0.7003174603174602)

**Feature Splitting**

In [15]:
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [17]:
df["Title"] = df["Name"].str.split(", ", expand=True)[1].str.split(".", expand=True)[0]

In [18]:
df[["Title", "Name"]]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [19]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)
# As we can see from this output the survival rate of Mrs and miss are higher than other survied marital status

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [20]:
# Now lets create a new column called marital status 

df["Is_married"] = 0
df["Is_married"]
# df["Is_married"].loc[df["Title"]== "Mrs"] = 1

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_married, Length: 891, dtype: int64

In [22]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Is_married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr,0

In [28]:
df["Is_married"] = np.where(df["Title"] == "Mrs",
                            "Yes",
                            np.where(
                                df["Title"] == "Mr",
                                "Yes",
                                df["Is_married"]
                            ))

In [29]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Is_married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,Yes
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,Yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,Yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr,Yes
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr,Yes